name: "Podcast Generator"
author: "Kaleb Weikel"
description: "Generates feed for podcast"
runs:
  using: "docker"
  image: "DockerFile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email:
    desriptions: The commiter's email
    required: true
    default: ${{ github.actor }}@localhost
  name: 
    desription: The commiter's name
    required: true
    default: ${{ github.actor }}